// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteEntriesIdData, DeleteEntriesIdErrors, DeleteEntriesIdResponses, GetEntriesData, GetEntriesErrors, GetEntriesMonthData, GetEntriesMonthErrors, GetEntriesMonthResponses, GetEntriesResponses, GetMeData, GetMeErrors, GetMeResponses, PostEntriesData, PostEntriesErrors, PostEntriesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List the current user's entries for a date (defaults to today)
 */
export const getEntries = <ThrowOnError extends boolean = false>(options?: Options<GetEntriesData, ThrowOnError>): RequestResult<GetEntriesResponses, GetEntriesErrors, ThrowOnError> => (options?.client ?? client).get<GetEntriesResponses, GetEntriesErrors, ThrowOnError>({ url: '/entries', ...options });

/**
 * Log a nice thing for today
 */
export const postEntries = <ThrowOnError extends boolean = false>(options: Options<PostEntriesData, ThrowOnError>): RequestResult<PostEntriesResponses, PostEntriesErrors, ThrowOnError> => (options.client ?? client).post<PostEntriesResponses, PostEntriesErrors, ThrowOnError>({
    url: '/entries',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete one of today's entries
 */
export const deleteEntriesId = <ThrowOnError extends boolean = false>(options: Options<DeleteEntriesIdData, ThrowOnError>): RequestResult<DeleteEntriesIdResponses, DeleteEntriesIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteEntriesIdResponses, DeleteEntriesIdErrors, ThrowOnError>({ url: '/entries/{id}', ...options });

/**
 * All-time day-by-day completion counts (calendar view)
 */
export const getEntriesMonth = <ThrowOnError extends boolean = false>(options?: Options<GetEntriesMonthData, ThrowOnError>): RequestResult<GetEntriesMonthResponses, GetEntriesMonthErrors, ThrowOnError> => (options?.client ?? client).get<GetEntriesMonthResponses, GetEntriesMonthErrors, ThrowOnError>({ url: '/entries/month', ...options });

/**
 * Current user profile plus today's progress
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({ url: '/me', ...options });
