// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000/api' | (string & {});
};

export type CreateEntryBodySchema = {
    content: string;
};

export type EntryDateQuerySchema = string;

export type EntryIdPathSchema = {
    id: number;
};

export type EntrySchema = {
    id: number;
    content: string;
    entryDate: string;
    createdAt: string;
};

export type MeSchema = {
    id: string;
    name: string;
    email: string;
    image: string | null;
    today: {
        date: string;
        count: number;
        complete: boolean;
    };
};

export type GetEntriesData = {
    body?: never;
    path?: never;
    query?: {
        date?: string;
    };
    url: '/entries';
};

export type GetEntriesErrors = {
    /**
     * Bad Request
     */
    400: {
        error?: string;
        code?: string;
    };
    /**
     * Successful response
     */
    401: {
        error: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        error?: string;
        code?: string;
    };
};

export type GetEntriesError = GetEntriesErrors[keyof GetEntriesErrors];

export type GetEntriesResponses = {
    /**
     * Successful response
     */
    200: {
        date: string;
        entries: Array<{
            id: number;
            content: string;
            entryDate: string;
            createdAt: string;
        }>;
        complete: boolean;
    };
};

export type GetEntriesResponse = GetEntriesResponses[keyof GetEntriesResponses];

export type PostEntriesData = {
    body: CreateEntryBodySchema;
    path?: never;
    query?: never;
    url: '/entries';
};

export type PostEntriesErrors = {
    /**
     * Bad Request
     */
    400: {
        error?: string;
        code?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        error?: string;
        code?: string;
    };
};

export type PostEntriesError = PostEntriesErrors[keyof PostEntriesErrors];

export type PostEntriesResponses = {
    /**
     * Created entry
     */
    201: EntrySchema;
};

export type PostEntriesResponse = PostEntriesResponses[keyof PostEntriesResponses];

export type DeleteEntriesIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/entries/{id}';
};

export type DeleteEntriesIdErrors = {
    /**
     * Bad Request
     */
    400: {
        error?: string;
        code?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        error?: string;
        code?: string;
    };
};

export type DeleteEntriesIdError = DeleteEntriesIdErrors[keyof DeleteEntriesIdErrors];

export type DeleteEntriesIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteEntriesIdResponse = DeleteEntriesIdResponses[keyof DeleteEntriesIdResponses];

export type GetEntriesMonthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/entries/month';
};

export type GetEntriesMonthErrors = {
    /**
     * Bad Request
     */
    400: {
        error?: string;
        code?: string;
    };
    /**
     * Successful response
     */
    401: {
        error: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        error?: string;
        code?: string;
    };
};

export type GetEntriesMonthError = GetEntriesMonthErrors[keyof GetEntriesMonthErrors];

export type GetEntriesMonthResponses = {
    /**
     * Successful response
     */
    200: {
        days: Array<{
            date: string;
            count: number;
            complete: boolean;
        }>;
    };
};

export type GetEntriesMonthResponse = GetEntriesMonthResponses[keyof GetEntriesMonthResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetMeErrors = {
    /**
     * Bad Request
     */
    400: {
        error?: string;
        code?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        error?: string;
        code?: string;
    };
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Successful response
     */
    200: MeSchema;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];
