// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteEntriesId, getEntries, getEntriesMonth, getMe, type Options, postEntries } from '../sdk.gen';
import type { DeleteEntriesIdData, DeleteEntriesIdError, DeleteEntriesIdResponse, GetEntriesData, GetEntriesError, GetEntriesMonthData, GetEntriesMonthError, GetEntriesMonthResponse, GetEntriesResponse, GetMeData, GetMeError, GetMeResponse, PostEntriesData, PostEntriesError, PostEntriesResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getEntriesQueryKey = (options?: Options<GetEntriesData>) => createQueryKey('getEntries', options);

/**
 * List the current user's entries for a date (defaults to today)
 */
export const getEntriesOptions = (options?: Options<GetEntriesData>) => queryOptions<GetEntriesResponse, GetEntriesError, GetEntriesResponse, ReturnType<typeof getEntriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEntries({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEntriesQueryKey(options)
});

/**
 * Log a nice thing for today
 */
export const postEntriesMutation = (options?: Partial<Options<PostEntriesData>>): UseMutationOptions<PostEntriesResponse, PostEntriesError, Options<PostEntriesData>> => {
    const mutationOptions: UseMutationOptions<PostEntriesResponse, PostEntriesError, Options<PostEntriesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postEntries({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete one of today's entries
 */
export const deleteEntriesIdMutation = (options?: Partial<Options<DeleteEntriesIdData>>): UseMutationOptions<DeleteEntriesIdResponse, DeleteEntriesIdError, Options<DeleteEntriesIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteEntriesIdResponse, DeleteEntriesIdError, Options<DeleteEntriesIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteEntriesId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEntriesMonthQueryKey = (options?: Options<GetEntriesMonthData>) => createQueryKey('getEntriesMonth', options);

/**
 * All-time day-by-day completion counts (calendar view)
 */
export const getEntriesMonthOptions = (options?: Options<GetEntriesMonthData>) => queryOptions<GetEntriesMonthResponse, GetEntriesMonthError, GetEntriesMonthResponse, ReturnType<typeof getEntriesMonthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEntriesMonth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEntriesMonthQueryKey(options)
});

export const getMeQueryKey = (options?: Options<GetMeData>) => createQueryKey('getMe', options);

/**
 * Current user profile plus today's progress
 */
export const getMeOptions = (options?: Options<GetMeData>) => queryOptions<GetMeResponse, GetMeError, GetMeResponse, ReturnType<typeof getMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMeQueryKey(options)
});
